In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/rashakil-ds/Public-Datasets/main/automobile.csv'
df = pd.read_csv(url)

In [2]:
df.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19     3.4              10.0        102   
4          136         mpfi  3.19     3.4               8.0        115   

   peak-rpm city-mpg highway-mpg  price  
0      5000       21          27  13495  
1      5000       21          27  16500  
2      5000       19          26  16500  
3      5500       24          30  13950  
4      5500       18          22  17450  

[5 rows x 26 columns]

In [4]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [7]:
import requests

url = 'https://raw.githubusercontent.com/rashakil-ds/Public-Datasets/main/automobile.csv'
filename = 'automobile.csv'

# Download the file content
response = requests.get(url)

# Save the content to a local file named 'automobile.csv'
if response.status_code == 200:
    with open(filename, 'wb') as f:
        f.write(response.content)
    print(f"File '{filename}' saved successfully.")
else:
    print(f"Error: Failed to download file. Status code: {response.status_code}")

File 'automobile.csv' saved successfully.


In [131]:
df
df1 = df.copy()  #Predicting Car Prices: linear regression
df2 = df.copy()  #Predicting Car Prices: KNN algorithm.

# Goal & Steps:

1. Predicting Car Prices:
   - Task: Build a regression model to predict the price (y=price) of cars based on other features in the dataset. This could involve preprocessing the data, selecting relevant features, and implementing `linear regression` and `KNN` algorithm.

2. Feature Engineering:
   - Task: Challenge students to come up with creative ways to engineer new features from the existing ones. For example, they could create a new feature representing the ratio of horsepower to curb weight.

3. Exploratory Data Analysis (EDA):
   - Task: Have students perform in-depth exploratory data analysis to understand the relationships between different features. Visualization tools can be used to communicate their findings effectively.

4. Handling Missing Data:
   - Task: Teach students how to handle missing data in a dataset. They can explore different strategies such as imputation or removal of missing values.

5. Training:
   - Task: Use relavant ML Models

6. Model evaluation:
- Evaluate models and Summarizing their findings. This should include a clear explanation of the model's performance and any insights gained from the analysis.

# *Predicting Car Prices:*
Task: Build a regression model to predict the price (y=price) of cars based on other features in the dataset. 
This could involve preprocessing the data, selecting relevant features, and implementing linear regression and KNN algorithm.

# *linear regression*

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('automobile.csv')

In [9]:
df1.shape

(202, 26)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          202 non-null    int64  
 1   normalized-losses  165 non-null    float64
 2   make               202 non-null    object 
 3   fuel-type          202 non-null    object 
 4   aspiration         202 non-null    object 
 5   num-of-doors       200 non-null    object 
 6   body-style         202 non-null    object 
 7   drive-wheels       202 non-null    object 
 8   engine-location    202 non-null    object 
 9   wheel-base         202 non-null    float64
 10  length             202 non-null    float64
 11  width              202 non-null    float64
 12  height             202 non-null    float64
 13  curb-weight        202 non-null    int64  
 14  engine-type        202 non-null    object 
 15  num-of-cylinders   202 non-null    object 
 16  engine-size        202 non

In [37]:
columns_with_nan = df1.isna().any()
columns_with_nan 

symboling            False
normalized-losses     True
make                 False
fuel-type            False
aspiration           False
num-of-doors          True
body-style           False
drive-wheels         False
engine-location      False
wheel-base           False
length               False
width                False
height               False
curb-weight          False
engine-type          False
num-of-cylinders     False
engine-size          False
fuel-system          False
bore                  True
stroke                True
compression-ratio    False
horsepower           False
peak-rpm             False
city-mpg             False
highway-mpg          False
price                False
dtype: bool

In [34]:
df1.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0      111.0   
1          130         mpfi  3.47    2.68               9.0      111.0   
2          152         mpfi  2.68    3.47               9.0      154.0   
3          109         mpfi  3.19    3.40              10.0      102.0   
4          136         mpfi  3.19    3.40               8.0      115.0   

   peak-rpm city-mpg  highway-mpg  price  
0    5000.0       21           27  13495  
1    5000.0       21           27  16500  
2    5000.0       19           26  16500  
3    5500.0       24           30  13950  
4    5500.0       18           22  17450  

[5 rows x 26 columns]

In [38]:
df1.isnull().sum()

symboling             0
normalized-losses    35
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [42]:
numeric_df1 = df1.select_dtypes(include=['number'])
print(numeric_df1.head())

   symboling  normalized-losses  wheel-base  length  width  height  \
0          3                NaN        88.6   168.8   64.1    48.8   
1          3                NaN        88.6   168.8   64.1    48.8   
2          1                NaN        94.5   171.2   65.5    52.4   
3          2              164.0        99.8   176.6   66.2    54.3   
4          2              164.0        99.4   176.6   66.4    54.3   

   curb-weight  engine-size  bore  stroke  compression-ratio  horsepower  \
0         2548          130  3.47    2.68                9.0       111.0   
1         2548          130  3.47    2.68                9.0       111.0   
2         2823          152  2.68    3.47                9.0       154.0   
3         2337          109  3.19    3.40               10.0       102.0   
4         2824          136  3.19    3.40                8.0       115.0   

   peak-rpm  city-mpg  highway-mpg  price  
0    5000.0        21           27  13495  
1    5000.0        21           27

In [43]:
x= df1[['curb-weight', 'horsepower', 'engine-size']]
y = df1['price']

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
reg = LinearRegression() #y=mx+c 

In [46]:
reg.fit(x,y)

LinearRegression()

In [47]:
reg.coef_   #value of m 

array([ 4.49406359, 48.79315666, 83.58706504])

In [48]:
reg.intercept_   #value of c

np.float64(-13862.424015693781)

In [49]:
reg.predict(x) #for all the area x given in the .csv file predict the rent y 

array([13870.80885823, 13870.80885823, 19043.69751303, 10728.09466479,
       15807.86542617, 14139.28148457, 15653.78091468, 16148.12790967,
       17787.20367833, 10856.37013136, 10856.37013136, 17928.73893787,
       18175.91243537, 19479.1908767 , 27003.45248823, 27677.56202685,
       28239.3199757 ,   265.62509458,  5497.80797332,  5655.100199  ,
        5409.20978718,  5409.20978718,  8869.37765889,  5818.16957394,
        5917.03897294,  5917.03897294,  9152.50366511, 12021.446908  ,
       18884.97860013,  4355.91998533,  5710.56754588,  3924.13833841,
        6254.34924037,  6326.25425782,  6568.93369172,  6631.85058199,
        9577.09080056,  9815.27617088,  9882.68712474, 10188.28344891,
       11338.12871279, 10516.35661851,  9724.23303498, 12762.59068079,
       34563.49689706, 34563.49689706, 43922.31741611,  5555.71374249,
        5600.6543784 ,  5623.12469635,  5802.88723998,  5825.35755794,
        7612.65070603,  7612.65070603,  7635.12102399, 10646.77631384,
      

In [50]:
df1['predicted_price'] = reg.predict(x) # assign a new column named predicted to dataframe1 to store the predicted y values

In [51]:
df1.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   fuel-system  bore  stroke  compression-ratio horsepower peak-rpm  city-mpg  \
0         mpfi  3.47    2.68                9.0      111.0   5000.0        21   
1         mpfi  3.47    2.68                9.0      111.0   5000.0        21   
2         mpfi  2.68    3.47                9.0      154.0   5000.0        19   
3         mpfi  3.19    3.40               10.0      102.0   5500.0        24   
4         mpfi  3.19    3.40                8.0      115.0   5500.0        18   

  highway-mpg  price  predicted_price  
0          27  13495     13870.808858  
1          27  16500     13870.808858  
2          26  16500     19043.697513  
3          30  13950     10728.094665  
4          22  17450     15807.865426  

[5 rows x 27 columns]

In [52]:
reg.score(x,y) #accuracy/score means 81% possibility of accurate result

0.8102362396115367

In [53]:
z = df1['predicted_price'] #accuracy/score means 100% possibility of accurate result

In [54]:
reg.score(x,z)

1.0

In [60]:
import matplotlib.pyplot as plt

x= df1[['curb-weight', 'horsepower', 'engine-size']]
y = df1['price']

plt.figure(figsize=(10,7))

m = reg.coef_[0]
c = reg.intercept_
equ = f"y={int(m):.2f}x + {int(c):.2f}"

plt.text(min(x), max(df1['price'])-50, equ)

plt.scatter(x,reg.predict(x),color='red', marker='*', label='Predicted_Price') #shift + tab

plt.scatter(x,reg.predict(x),color='red', marker='*') #shift + tab

plt.scatter(x, 
            df1['price'], 
            c=x, 
            cmap='coolwarm', 
            s=60, 
            alpha=.90,
            edgecolor='k',
            label='Original') #shift + tab

plt.xlabel('Features in X', fontsize=10)
plt.ylabel('Price in CAD',fontsize=10)
plt.title('Features VS. Price',fontsize=15, weight='bold')

plt.plot(x, df1['predicted_price'], color='black')

plt.legend()
plt.show()

ValueError: x and y must be the same size

Error in callback <function _draw_all_if_interactive at 0x000001605B13B6A0> (for post_execute), with arguments args (),kwargs {}:


ConversionError: Failed to convert value(s) to axis units: 'curb-weight'

ConversionError: Failed to convert value(s) to axis units: 'curb-weight'

<Figure size 1000x700 with 1 Axes>

# *Predicting Car Price Using KNN Algorithm*

In [61]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor # NEW IMPORT for KNN
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import r2_score

In [62]:
df2.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19     3.4              10.0        102   
4          136         mpfi  3.19     3.4               8.0        115   

   peak-rpm city-mpg highway-mpg  price  
0      5000       21          27  13495  
1      5000       21          27  16500  
2      5000       19          26  16500  
3      5500       24          30  13950  
4      5500       18          22  17450  

[5 rows x 26 columns]

In [93]:
# Replace non-numeric values ('?') with NaN
df2['horsepower'] = df2['horsepower'].replace('?', np.nan)

In [96]:
# Convert columns to numeric, forcing errors to NaN
df2['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [97]:
# Drop rows where any of the critical features or price are missing
df2.dropna(subset=['horsepower', 'engine-size', 'curb-weight', 'price'], inplace=True)

In [98]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 201
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          200 non-null    int64  
 1   normalized-losses  165 non-null    float64
 2   make               200 non-null    object 
 3   fuel-type          200 non-null    object 
 4   aspiration         200 non-null    object 
 5   num-of-doors       198 non-null    object 
 6   body-style         200 non-null    object 
 7   drive-wheels       200 non-null    object 
 8   engine-location    200 non-null    object 
 9   wheel-base         200 non-null    float64
 10  length             200 non-null    float64
 11  width              200 non-null    float64
 12  height             200 non-null    float64
 13  curb-weight        200 non-null    int64  
 14  engine-type        200 non-null    object 
 15  num-of-cylinders   200 non-null    object 
 16  engine-size        200 non-null

In [99]:
df2.isnull().sum()

symboling             0
normalized-losses    35
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  0
stroke                0
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [100]:
df2_x= df2[['curb-weight', 'horsepower', 'engine-size']]
df2_y = df2['price']

In [102]:
x_train, x_test, y_train, y_test = train_test_split(df2_x, df2_y, test_size=0.2, random_state=42)

In [103]:
len(x_train)

160

In [104]:
len(x_test)

40

In [105]:
len(y_train)

160

In [106]:
len(y_test)

40

In [107]:
# Initialize the KNN Regressor (using k=5 neighbors)
knn_reg = KNeighborsRegressor(n_neighbors=5)

In [108]:
# Fit the KNN model using the training data
knn_reg.fit(x_train,y_train)

KNeighborsRegressor()

In [115]:
# Predict prices using the test set
y_predict_knn = knn_reg.predict(x_test)


In [116]:
y_predict_knn

array([ 7105.2, 20329.2,  5608.4,  8423.4, 16162.4,  6300.6, 28569.4,
        9632.4, 17099.4, 36032.4, 17516.2,  9474.4, 16162.4,  9495.4,
       12025.4,  8480.6, 11047.4,  7794.2,  9373.4, 32997.4, 21023. ,
       23257.2,  7851.8,  6325.4, 32997.4, 10189.8, 10868. , 32997.4,
       17477. ,  7356. , 10844.2,  5747.6, 12070. ,  6955.2,  7337. ,
       18362. ,  8116.6,  9785.4, 15313. ,  8116.6])

In [118]:
# Evaluate the model's performance using R-squared
score_knn = r2_score(y_test, y_predict_knn)

In [119]:
score_knn #(using k=5 neighbors)

0.6960578141097469

In [120]:
# Initialize the KNN Regressor (using k=6 neighbors)
knn_reg = KNeighborsRegressor(n_neighbors=6)

In [121]:
# Fit the KNN model using the training data
knn_reg.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [122]:
# Predict prices using the test set
y_predict_knn = knn_reg.predict(x_test)

In [123]:
y_predict_knn

array([ 7220.83333333, 19723.5       ,  5689.5       ,  8362.5       ,
       15684.5       ,  6392.        , 29807.83333333,  9362.5       ,
       17407.83333333, 32872.83333333, 17588.5       ,  9139.16666667,
       16053.66666667,  9504.33333333, 11686.        ,  8335.33333333,
       10913.66666667,  7739.        , 10136.16666667, 29807.83333333,
       19646.5       , 22163.5       ,  8125.66666667,  6539.33333333,
       29807.83333333,  9907.33333333, 10764.16666667, 32872.83333333,
       18233.83333333,  7211.33333333, 10701.5       ,  5922.16666667,
       11545.16666667,  6687.33333333,  7447.33333333, 17898.33333333,
        8106.83333333,  9737.        , 14709.83333333,  8106.83333333])

In [124]:
# Evaluate the model's performance using R-squared
score_knn = r2_score(y_test, y_predict_knn)

In [126]:
score_knn   #(using k=6 neighbors)

0.6854998250496163

In [128]:
# --- OLD LINEAR REGRESSION (Kept for comparison) ---

# Initialize the Linear Regression object
reg = LinearRegression()

# Fit the model using multiple features (X) and 'price' as the target (y)

reg.fit(x_train, y_train)
y_pred_linear = reg.predict(x_test)
score_linear = r2_score(y_test, y_pred_linear)


In [129]:
y_pred_linear

array([ 6982.0346321 , 25572.54939207,  5970.70514848,  7980.65166528,
       13355.77564078,  6001.03185992, 27992.26534977, 11510.45719298,
       20653.84559711, 32264.18354727, 22140.00073715, 10254.94694251,
       15514.26127661, 10988.55509542,  9537.31757554,  9347.18637253,
       11114.86137069,  8765.99440133, 11156.27334573, 28241.5762624 ,
       22412.25466596, 26139.16510259,  7643.46643515,  6814.31638178,
       23295.8967866 , 10717.41861673, 11327.2662198 , 23386.55530028,
       22611.70339606,  7172.41751083, 10641.44652776,  5867.61837418,
       10079.91552507,  6545.15542259,  7423.10180614, 14268.20631462,
        8880.88028528, 10161.01225987, 15355.60887767,  8769.77295974])

In [130]:
score_linear   #this is higher than KNN algorithm

0.7742009298109513